Organizations:

  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: organizations/ordererOrganizations/medchain.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer1.medchain.id:7050
      - orderer2.medchain.id:8050
      - orderer3.medchain.id:9050

  - &Klinik
    Name: KlinikMSP
    ID: KlinikMSP
    MSPDir: organizations/peerOrganizations/klinik.medchain.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('KlinikMSP.admin', 'KlinikMSP.peer', 'KlinikMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('KlinikMSP.admin', 'KlinikMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('KlinikMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('KlinikMSP.peer')"
    AnchorPeers:
      - Host: peer0.klinik.medchain.id
        Port: 7051

  - &Akademik
    Name: AkademikMSP
    ID: AkademikMSP
    MSPDir: organizations/peerOrganizations/akademik.medchain.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AkademikMSP.admin', 'AkademikMSP.peer', 'AkademikMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AkademikMSP.admin', 'AkademikMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AkademikMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AkademikMSP.peer')"
    AnchorPeers:
      - Host: peer0.akademik.medchain.id
        Port: 9051

  - &Dokter
    Name: DokterMSP
    ID: DokterMSP
    MSPDir: organizations/peerOrganizations/dokter.medchain.id/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DokterMSP.admin', 'DokterMSP.peer', 'DokterMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('DokterMSP.admin', 'DokterMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('DokterMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('DokterMSP.peer')"
    AnchorPeers:
      - Host: peer0.dokter.medchain.id
        Port: 10051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer1.medchain.id:7050
    - orderer2.medchain.id:8050
    - orderer3.medchain.id:9050
  EtcdRaft:
    Consenters:
      - Host: orderer1.medchain.id
        Port: 7050
        ClientTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer1.medchain.id/tls/server.crt
        ServerTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer1.medchain.id/tls/server.crt
      - Host: orderer2.medchain.id
        Port: 8050
        ClientTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer2.medchain.id/tls/server.crt
        ServerTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer2.medchain.id/tls/server.crt
      - Host: orderer3.medchain.id
        Port: 9050
        ClientTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer3.medchain.id/tls/server.crt
        ServerTLSCert: organizations/ordererOrganizations/medchain.id/orderers/orderer3.medchain.id/tls/server.crt
    Options:
      TickInterval: 500ms
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: 16777216
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      MedConsortium:
        Organizations:
          - *Klinik
          - *Akademik
          - *Dokter

  ThreeOrgsChannel:
    <<: *ChannelDefaults
    Consortium: MedConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Klinik
        - *Akademik
        - *Dokter
      Capabilities:
        <<: *ApplicationCapabilities